export const PERSONS = [
  {
    name: "Dylan Gutierrez",
    image: "/images/person1.webp",
    job_position: "CEO & Founder",
    twitter_link: "https://www.twitter.com/dgutierrez",
    ig_link: "https://www.instagram.com/dgutierrez",
    linkedin_link: "https://www.linkedin.com/in/dgutierrez",
  },
  {
    name: "Jessica Rodriguez",
    image: "/images/person2.webp",
    job_position: "Managing Director",
    twitter_link: "https://www.twitter.com/jrodriguez",
    ig_link: "https://www.instagram.com/jrodriguez",
    linkedin_link: "https://www.linkedin.com/in/jrodriguez",
  },
  {
    name: "Mackenzie Turner",
    image: "/images/person3.webp",
    job_position: "Product Designer",
    twitter_link: "https://www.twitter.com/mturner",
    ig_link: "https://www.instagram.com/mturner",
    linkedin_link: "https://www.linkedin.com/in/mturner",
  },
  {
    name: "Antonio Harris",
    job_position: "Software Engineer",
    image: "/images/person4.webp",
    twitter_link: "https://www.twitter.com/aharris",
    ig_link: "https://www.instagram.com/aharris",
    linkedin_link: "https://www.linkedin.com/in/aharris",
  },
  {
    name: "Victor Gibson",
    image: "/images/person5.webp",
    job_position: "Marketing Specialist",
    twitter_link: "https://www.twitter.com/vgibson",
    ig_link: "https://www.instagram.com/vgibson",
    linkedin_link: "https://www.linkedin.com/in/vgibson",
  },
  {
    name: "Jordan Carter",
    image: "/images/person6.webp",
    job_position: "Social Media Manager",
    twitter_link: "https://www.twitter.com/jcarter",
    ig_link: "https://www.instagram.com/jcarter",
    linkedin_link: "https://www.linkedin.com/in/jcarter",
  },
];
